import Head from "next/head";

import styles from "@/styles/Home.module.css";
import Header from "@/components/header";
import Search from "@/components/Search";
import HeroSection from "@/components/heroSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Etherscan Clone Using Moralis API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.name}>
        {/* <p>All the components gonna be here</p> */}
        <Header/>
        <Search/>
        <HeroSection/>
      </section>
    </>
  );
}
